version: "3.8"

services:
  # Node.js app
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    env_file:
      - .env.example
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

  # MongoDB service
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
